// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgoUiGaqre15DKaqFMRRGtdiPsZIe3_8',
    appId: '1:788000672662:web:b510e14b0974551b1b6bb7',
    messagingSenderId: '788000672662',
    projectId: 'mentalhealth-8d43a',
    authDomain: 'mentalhealth-8d43a.firebaseapp.com',
    storageBucket: 'mentalhealth-8d43a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2i-lPvDmP6IAu-XPhde6NcDi4MH03Oac',
    appId: '1:788000672662:android:3ad0979b3b4378c61b6bb7',
    messagingSenderId: '788000672662',
    projectId: 'mentalhealth-8d43a',
    storageBucket: 'mentalhealth-8d43a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0g8LRLquvDXZlokh6u_EPhTECyS38gI',
    appId: '1:788000672662:ios:a6f455f1f4eb7e5d1b6bb7',
    messagingSenderId: '788000672662',
    projectId: 'mentalhealth-8d43a',
    storageBucket: 'mentalhealth-8d43a.firebasestorage.app',
    iosClientId: '788000672662-7mme3p4pesrj6755i65ubtrivg4f8rkk.apps.googleusercontent.com',
    iosBundleId: 'com.mindmate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0g8LRLquvDXZlokh6u_EPhTECyS38gI',
    appId: '1:788000672662:ios:a6f455f1f4eb7e5d1b6bb7',
    messagingSenderId: '788000672662',
    projectId: 'mentalhealth-8d43a',
    storageBucket: 'mentalhealth-8d43a.firebasestorage.app',
    iosClientId: '788000672662-7mme3p4pesrj6755i65ubtrivg4f8rkk.apps.googleusercontent.com',
    iosBundleId: 'com.mindmate.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKgoUiGaqre15DKaqFMRRGtdiPsZIe3_8',
    appId: '1:788000672662:web:c7863c73f49bec551b6bb7',
    messagingSenderId: '788000672662',
    projectId: 'mentalhealth-8d43a',
    authDomain: 'mentalhealth-8d43a.firebaseapp.com',
    storageBucket: 'mentalhealth-8d43a.firebasestorage.app',
  );

}